USE mysql;
USE inspire;

/*
select : 데이터를 검색할 때 사용하는 문법

SELECT 	column_name | * | 표현식이나 함수를 포함하는 식 | [as] 별칭 | distinct
FROM 		table-name ;
[WHERE]		-- 행의 제한
[GROUP BY]	-- 하위데이터 그룹 생성
[HAVING]		-- 그룹에 대한 조건
[ORDER BY]	-- 정렬(ASC, DESC)

컬럼명은 대소문자를 구별하지 않는다.
키워드는 대문자로 작성하는게 원칙
*/
SELECT 	*
FROM 		employee;

SELECT 	emp_id,
			emp_name
FROM		employee;

/*
별칭 사용시 공백, 특수문자, 숫자를 포함할 경우 ``으로
*/
SELECT 	emp_id AS `사원 번호`,
			emp_name AS `사원 이름`
FROM		employee;

/*
NULL 치환할 수 있는 함수가 있지않을까?
*/
SELECT	EMP_NAME,
			SALARY,
			SALARY * 12 + IFNULL(BONUS_PCT, 0) AS `연봉`
FROM 		employee;

SELECT IFNULL('하이', '넌 누구냐?'), NULLIF(NULL, '널 이구나');

-- DISTINCT : 컬럼에 포함된 중복값을 한번씩만 출력할 때
-- SELECT절에 한번만
SELECT 	DISTINCT	DEPT_ID, JOB_ID
FROM 		employee;

SELECT 	*
FROM		sal_grade;

SELECT 	*
FROM		country;

-- 부모의 기본 키와 자식의 외래 키가 다를 수 있다.
SELECT 	*
FROM		location;

SELECT 	*
FROM		department;

-- Q) 90번 부서의 모든 사원정보를 검색한다면?
-- where (제한 행)
-- 연산자 : 비교(LIKE, NOT LIKE), 산술, 논리(AND, OR, NOT)
SELECT	*
FROM		employee
WHERE 	DEPT_ID = '90';

SELECT	*
FROM		employee
WHERE 	JOB_ID = 'j2';

-- 사원테이블에서 부서번호가 90번이거나 급여가 4000000이상인 사원의 모든 정보를 검색한다면?
SELECT 	*
FROM 		employee
WHERE		DEPT_ID ='90' && SALARY >= 4000000;

-- CONCAT() : 연결연산자
SELECT 	CONCAT('임정섭', '강사님은','??');

SELECT 	CONCAT(EMP_NAME, '님의 급여는 ', SALARY, '원 입니다.') AS `급여정보(원)`
FROM 		employee;

-- 급여가 3500000 이상이고 5500000 이하인 사원의 이름, 직급, 급여를 검색한다면?
-- BETWEEN ~ AND
SELECT 	emp_name, JOB_ID, SALARY
FROM 		employee
WHERE 	SALARY BETWEEN 3500000 AND 5500000;

-- LIKE 패턴검색연산자(%,_)
-- % : 모든 문자를 매칭
-- _ : 하나의 문자를 매칭

-- Q) 사원테이블에서 김씨 성을 가진 사원의 모든 정보를 검색한다면?
SELECT 	*
FROM 		employee;

SELECT 	*
FROM 		employee
WHERE 	EMP_NAME LIKE '김%' ;

-- Q) 사원테이블에서 부서배치를 받지않은 사원의 모든 정보를 검색한다면?
SELECT 	*
FROM 		employee
WHERE 	DEPT_ID IS NULL;

-- Q) 사원테이블에서 부서번호가 60 이거나 90번인  사원의 모든 정보를 검색한다면?
-- 이거나(OR) == IN()
SELECT	*
FROM		employee
WHERE 	DEPT_ID IN('60', '90');

SELECT 	*
FROM 		tb_student;
-- 1)
SELECT DEPARTMENT_NAME AS `학과 명`, CATEGORY AS '계열'
FROM tb_department;

-- 2)
SELECT CONCAT(department_NAME, '의', ' 정원은 ', CAPACITY, '입니다.')
FROM tb_department ;

-- 3)
-- SUBSTRING(문자열, 시작위치, 길이)
SELECT S.STUDENT_NAME
FROM TB_STUDENT S
JOIN tb_department D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE D.DEPARTMENT_NAME = '국어국문학과'
AND SUBSTRING(S.STUDENT_SSN, 8, 1) IN ('2', '4')
AND S.ABSENCE_YN = 'Y';

SELECT	S.STUDENT_NAME, 
			S.STUDENT_SSN,
			S.ABSENCE_YN
FROM		tb_student S 
WHERE		S.DEPARTMENT_NO = '001' 
AND		S.ABSENCE_YN = 'Y'
AND 		S.STUDENT_SSN LIKE '_______2%';

-- 4)
SELECT STUDENT_NAME
FROM tb_student
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5)
SELECT department_name, category
FROM tb_department
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6)
SELECT PROFESSOR_NAME
FROM tb_proFessor
WHERE DEPARTMENT_NO IS NULL;

-- 7)
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8)
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9)
SELECT DISTINCT CATEGORY
FROM tb_department;
-- ORDER BY CATEGORY;

-- 10)
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE YEAR(ENTRANCE_DATE) = 2002
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N';


/*
내장함수란?
함수의 유형
- 단일행 함수 : 문자, 날짜, 숫자, 기타변환함수~
- 복수행 함수 : MIN, MAX, SUM, COUNT, AVG ~

사용위치
- SELECT, WHERE, GROUP BY, HAVING, ORDER BY
*/

-- 문자열 함수
-- LENGTH, CONCAT, SUBSTRING, LEFT, RIGHT, INSTR, REPLACE, UPPER, LOWER, TRIM, PAD ETC...
SELECT 	LENGTH('임정섭'),
			LENGTH('JSLIM'),
			CHAR_LENGTH('임정섭');
			
SELECT	EMP_NAME,
			LENGTH(EMP_NAME)
FROM		employee;

SELECT	UPPER('hello'), LOWER('HELLO');

-- TRIM(), LTRIM(), RTRIM()
SELECT	LENGTH(' HELLO '), LENGTH(TRIM(' HELLO ')),
			LENGTH(LTRIM(' HELLO ')), LENGTH(RTRIM(' HELLO '));
			
-- 문자열을 채우는 패딩 : LPAD(STR, LENGTH, PAD_STR), RPAD()
SELECT 	LPAD('5', 3, '0'), RPAD('5', 3, 'A');

SELECT	EMAIL,
			LENGTH(EMAIL),
			LPAD(EMAIL, 20, '*'),
			LENGTH(LPAD(EMAIL, 20, '*'))
FROM employee;

-- SUBSTRING() : 부분문자열을 반환하는 함수
SELECT	SUBSTRING('ABCDEFG', 2, 4),
			LEFT('ABCDEFG', 2),
			RIGHT('ABCDEFG', 2);
			
SELECT	SUBSTRING('THIS IS INSPIRE CAMP' FROM 9 FOR 7),
			SUBSTRING('THIS IS INSPIRE CAMP', 9, 7),
			SUBSTRING_INDEX('www.lgcns.com', '.', -1);
			
-- INSTR() : 부분문자열의 인덱스를 반환하는 함수
SELECT	INSTR('LGCNS CAMP', 'CAMP');

SELECT	*
FROM employee;
-- Q) .앞의 문자 'C' 인덱스 번지를 검색
-- Q) 메일 아이디만 추출(substring_index())
SELECT	EMAIL,
			INSTR(EMAIL, 'c.'),
			SUBSTRING(EMAIL, 1, INSTR(EMAIL, '@')-1),
			SUBSTRING_INDEX(EMAIL, '@', 1)
FROM 		employee;

-- 문자열 반복
SELECT 	REPEAT('LGCNS',3);

-- 문자열 치환
SELECT 	REPLACE('오늘은 즐거운  화요일', '즐거운', '재미있는');

-- Q) 입사년도만 추출
-- Q) 주민번호 앞 6자리만 추출
-- Q) 입사일을 ****년 **월 **일 형식으로 추출

SELECT 	CONCAT(SUBSTRING_INDEX(HIRE_DATE, '-', 1), '년') AS `입사년도`,
			SUBSTRING_INDEX(EMP_NO, '-', 1) AS `생년월일`,
			CONCAT(YEAR(HIRE_DATE), '년 ', LPAD(MONTH(HIRE_DATE), 2, 0), '월 ', LPAD(DAY(HIRE_DATE), 2, 0), '일') AS `입사일`,
			DATE_FORMAT(HIRE_DATE, '%Y년 %m월 %d일') AS `입사일`
FROM 		employee;

-- 숫자함수
SELECT	ABS(-100),
			CEILING(4.7),
			CEILING(4.1),
			FLOOR(4.7),
			FLOOR(4.1),
			ROUND(4.5),
			ROUND(4.412345, 2),
			TRUNCATE(123.45678, 2),
			TRUNCATE(123.45678, -2),
			((RAND() * 100 ) +1),
			GREATEST(10, 20, 30),
			LEAST(10, 20, 30);
			
-- 날짜함수
-- ADDDATE(), DATEDIFF()
SELECT	NOW(),
			SYSDATE(),
			CURDATE(),
			CURTIME();
			
SELECT	HIRE_DATE,
			CAST(HIRE_DATE + 1 AS DATE)
FROM		employee;

-- Q) 입사일을 기준으로 근속년수가 30년이 되는 일자를 조회하고 싶다면?
SELECT	HIRE_DATE,
			ADDDATE(HIRE_DATE, INTERVAL 30 YEAR),
			ADDDATE(CURDATE(), INTERVAL 2 MONTH),
			ADDDATE(CURDATE(), INTERVAL 2 DAY)
FROM 		employee;

-- Q) 오늘 날짜를 기준으로 근속년수가 30년 이상인 사원의 모든 정보를 검색한다면?
SELECT 	*, 
			FLOOR(DATEDIFF(CURDATE(), HIRE_DATE)/365) AS '근속년수'
FROM 		employee
-- WHERE ADDDATE(HIRE_DATE, INTERVAL 30 YEAR) <= CURDATE();
WHERE 	DATEDIFF(CURDATE(), HIRE_DATE) >= 30*365;


-- D DEFINITION L
CREATE TABLE COUPON_TBL(
	CREATE_DATE DATE,
	END_DATE DATE
);

INSERT INTO coupon_tbl VALUES( NOW() , ADDDATE(NOW(), INTERVAL 7 DAY));

SELECT	*
FROM 		coupon_tbl;

-- SUBDATE(), SUBTIME()
SELECT 	SUBDATE(NOW(), INTERVAL 30 DAY),
			SUBTIME(NOW(), '01:30:00');
			
-- YEAR(), MONTH(), DAY(), HOUR(), MINUTE(), SECOND()
SELECT	HIRE_DATE,
			SUBSTRING(HIRE_DATE, 1, 4),
			CAST(YEAR(HIRE_DATE) AS CHAR),
			CAST(MONTH(HIRE_DATE) AS CHAR),
			CAST(DAY(HIRE_DATE) AS CHAR),
			CAST(HOUR(HIRE_DATE) AS CHAR),
			CAST(MINUTE(HIRE_DATE) AS CHAR),
			CAST(SECOND(HIRE_DATE) AS CHAR)
FROM 		employee;

-- WEEKDAY() : 날짜의 요일을 정수로 변환(0 : 월요일)
-- DAYOFWEEK() : 요일을 숫자로 변환(1 : 일요일)
-- Q) 2020년 크리스마스는 무슨 요일인가요?
SELECT	WEEKDAY('2020-12-25'),
			DAYOFWEEK('2020-12-25'),
			DAYNAME('2020-12-25');


-- 기타함수
-- 흐름제어 함수(IF, IFNULL, NULLIF, CASE ~ WHEN ~ THEN ~ END)

SELECT	IF(100 > 200, '참', '거짓');
SELECT	CASE	10
				WHEN 1 THEN '1'
				WHEN 10 THEN '10'
				ELSE '내가 원하는 값이 아님'
			END AS `구분`;
			
SELECT 	*
FROM 		employee;
-- Q) 부서번호가 50번인 사원의 이름, 주민번호, 성별을 검색한다면?
SELECT	EMP_NAME,
			EMP_NO,
			IF( SUBSTRING(EMP_NO, 8, 1) IN (2,4) , '여자', '남자') AS `GENDER`
FROM		EMPLOYEE
WHERE		DEPT_ID = '50' ;

-- BAD CASE CASE - WHEN - THEN의 경우 정확한 값 비교만 가능
SELECT 	EMP_NAME, 
			EMP_NO, 
			CASE SUBSTRING(EMP_NO, INSTR(EMP_NO, '-')+1, 1)
				WHEN 1 OR 3 THEN '남'
				WHEN 2 OR 4 THEN '여'
				ELSE 'ERROR'
			END AS '성별'
FROM		employee
WHERE DEPT_ID = '50';
-- 수정
SELECT 	EMP_NAME, 
			EMP_NO, 
			CASE 	WHEN SUBSTRING(EMP_NO, INSTR(EMP_NO, '-')+1, 1) IN ('1', '3') THEN '남'
					WHEN SUBSTRING(EMP_NO, INSTR(EMP_NO, '-')+1, 1) IN ('2', '4') THEN '여'
				ELSE 'ERROR'
			END AS '성별'
FROM		employee
WHERE DEPT_ID = '50';

-- Q) 사원테이블의 직급(JOB_ID)이 J4인 사원 사번, 이름, 사수번호 검색한다면?
-- 추가) 사수번호가 없는 사원은 MGR_ID 컬럼에 '관리자'로 출력

SELECT	EMP_ID,
			EMP_NAME,
			IF(MGR_ID = '', '관리자', MGR_ID)
FROM		employee
WHERE		JOB_ID = 'J4';


-- Q) 급여등급을 나눠보고 싶다
-- 300 이하면 초급, 400 이하면 중급, 초과하면 고급
-- 사원번호, 이름, 급여, 급여등급 검색하고 싶다면?

SELECT	EMP_ID,
			EMP_NAME,
			SALARY,
			IF(SALARY <= 3000000, '초급', IF(SALARY <=4000000, '중급', '고급')) AS '급여등급'
FROM		employee;

-- Day05.  DDL 
-- mysqlAdditional SELECT - Option	[실습 ~ ]											

-- Q10)
SELECT	S.STUDENT_NO,
			S.STUDENT_NAME,
			ROUND(AVG(G.`POINT`),1 )
FROM		tb_department	D
JOIN		tb_student 		S	ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN		tb_grade 		G  ON(S.STUDENT_NO = G.STUDENT_NO) 
WHERE		D.DEPARTMENT_NAME = '음악학과' 
GROUP BY S.STUDENT_NO ; 



-- Q14)
SELECT	S.STUDENT_NAME,
			CASE 	WHEN S.COACH_PROFESSOR_NO IS NULL THEN '지도교수 미지정'
					ELSE P.PROFESSOR_NAME
			END 	AS `지도교수`
FROM				tb_department	D
JOIN				tb_student 		S	ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
LEFT JOIN		tb_PROFESSOR 	P  ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE				D.DEPARTMENT_NAME = '서반아어학과' ; 


-- Q15)
SELECT 		ts.STUDENT_NO								AS '학번'
					, ts.STUDENT_NAME 					AS '이름'
					, 		td.DEPARTMENT_NAME 			AS '학과 이름'
					, 		ROUND(AVG(tg.`POINT`),2) 	AS '평점'
FROM 			TB_STUDENT ts
JOIN 			TB_GRADE tg 							ON ( ts.STUDENT_NO = tg.STUDENT_NO )
JOIN 			TB_DEPARTMENT td 						ON ( td.DEPARTMENT_NO = ts.DEPARTMENT_NO )
WHERE 		ts.ABSENCE_YN = 'N'
GROUP BY 	ts.STUDENT_NO, ts.STUDENT_NAME , td.DEPARTMENT_NAME
HAVING 		AVG(tg.`POINT` ) >= 4 ;




-- Q18)
SELECT	S.STUDENT_NO,
			S.STUDENT_NAME			
FROM		tb_department	D
JOIN		tb_student 		S	ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN		tb_grade 		G  ON(S.STUDENT_NO = G.STUDENT_NO) 
WHERE		D.DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NO,	S.STUDENT_NAME 
ORDER BY AVG(G.`POINT`) DESC 
LIMIT 1 ; 


-- Q19)
SELECT	D.DEPARTMENT_NAME,
			ROUND(AVG(G.`POINT`),1)
FROM		tb_department	D
JOIN		tb_student 		S	ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN		tb_grade 		G  ON(S.STUDENT_NO = G.STUDENT_NO)
JOIN		tb_class			C  ON(C.CLASS_NO = G.CLASS_NO)	
WHERE 	D.CATEGORY = (	SELECT	D.CATEGORY
								FROM		tb_department D
								WHERE		D.DEPARTMENT_NAME = '환경조경학과') 
AND		C.CLASS_TYPE LIKE '%전공%'
GROUP BY D.DEPARTMENT_NAME ;

							
/*
DDL
- 물리적 저장공간인 테이블 생성과 논리적 저장공간인 VIEW 

CREATE TABLE TABLE_NAME(
	COLUMN_NAME DATATYPE(SIZE) [DEFAULT] [CONSTRAINT TYPE],
	[CONSTRAINT TYPE] COLUMN_NAME 
);

- DEFAULT : 묵시적으로 NULL 입력되었을 때 해당 컬럼의 값을 DEFAULT 값으로 대체 
- CONSTRAINT(제약) : NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY, CHECK 
- 컬럼레벨의 제약, 테이블 레벨의 제약(NOT NULL x)  
 

- DROP, ALTER
DML
- INSERT, UPDATE, DELETE

Object : TABLE, VIEW, INDEX, SEQUENCE, ETC...
*/

DROP TABLE IF EXISTS USER_TBL ; 
CREATE TABLE USER_TBL (
	USER_ID		VARCHAR(50),
	USER_NAME	VARCHAR(50),
	BIRTHYEAR	DATE CHECK( BIRTHYEAR >= '2026-06-19' ),
	ADDRESS		VARCHAR(100),
	REGDATE		DATE,
	CONSTRAINT 	PRIMARY KEY (USER_ID)
);

SELECT	*
FROM		USER_TBL ;

-- DML
INSERT INTO  user_tbl(USER_ID, USER_NAME, BIRTHYEAR)
VALUES('JSLIM', '임정섭', '2026-06-19') ;

INSERT INTO  user_tbl(USER_ID, USER_NAME, BIRTHYEAR)
VALUES(NULL, '임정섭', '2026-06-19') ;

SHOW INDEX FROM user_tbl ;


-- FOREIGN KEY (참조무결성) 
-- ON DELETE CASCADE, ON UPDATE CASCADE
-- ON DELETE ON ACTION, ON UPDATE NO ACTION 

DROP TABLE IF EXISTS JOB_TBL ; 
CREATE TABLE JOB_TBL (
	JOB_ID 		VARCHAR(10) ,
	JOB_TITLE	VARCHAR(50) ,
	CONSTRAINT PRIMARY KEY (JOB_ID)
);

INSERT INTO JOB_TBL 
VALUES('J1', '기획팀');

INSERT INTO JOB_TBL 
VALUES('J1', '교육팀');

SELECT	*
FROM	 	JOB_TBL ;


DROP TABLE IF EXISTS DEPT_TBL ; 
CREATE TABLE DEPT_TBL (
	DEPT_ID 		VARCHAR(10) ,
	DEPT_NAME	VARCHAR(50) ,
	CONSTRAINT PRIMARY KEY (DEPT_ID)
);

INSERT INTO DEPT_TBL 
VALUES('10', 'XXXX');

SELECT	*
FROM	 	DEPT_TBL ;



DROP TABLE IF EXISTS EMP_TBL ; 
CREATE TABLE EMP_TBL(
	EMP_ID		VARCHAR(10),
	EMP_NAME		VARCHAR(50),
	JOB_ID		VARCHAR(10) NOT NULL , 
	DEPT_ID		VARCHAR(10) NOT NULL ,
	CONSTRAINT  FOREIGN KEY (DEPT_ID) REFERENCES DEPT_TBL(DEPT_ID) ON DELETE CASCADE ,
	CONSTRAINT  FOREIGN KEY (JOB_ID)  REFERENCES JOB_TBL(JOB_ID) ON UPDATE CASCADE ,
	CONSTRAINT  PRIMARY KEY (EMP_ID)	 
);

SELECT	*
FROM	 	EMP_TBL ;

INSERT INTO EMP_TBL VALUES('100', '임정섭', 'J1', '10') ;
INSERT INTO EMP_TBL VALUES('200', '임정섭', 'J1', '10') ;
 
-- 참조무결성의 삭제 
DELETE	
FROM		JOB_TBL 
WHERE		JOB_ID = 'J1' ; 

DELETE	
FROM		DEPT_TBL 
WHERE		DEPT_ID = '10' ;
 

-- CHECK, DEFAULT 

DROP TABLE IF EXISTS EMP_TBL ; 
CREATE TABLE EMP_TBL(
	EMP_ID		VARCHAR(10),
	EMP_NAME		VARCHAR(50),
	SALARY		INT				CHECK( SALARY > 0 ),
	GENDER		CHAR(1)			CHECK( GENDER IN('M', 'F')),
	REG_DATE		DATE				DEFAULT SYSDATE(),
	JOB_ID		VARCHAR(10) 	NOT NULL , 
	DEPT_ID		VARCHAR(10) 	NOT NULL ,
	CONSTRAINT  FOREIGN KEY (DEPT_ID) REFERENCES DEPT_TBL(DEPT_ID) ON DELETE CASCADE ,
	CONSTRAINT  FOREIGN KEY (JOB_ID)  REFERENCES JOB_TBL(JOB_ID) ON UPDATE CASCADE ,
	CONSTRAINT  PRIMARY KEY (EMP_ID)	 
);
SELECT	*
FROM	 	EMP_TBL ;

INSERT INTO EMP_TBL(EMP_ID, SALARY, GENDER, JOB_ID, DEPT_ID) 
VALUES('100', 100, 'M', 'J1', '10') ;

INSERT INTO EMP_TBL(EMP_ID, SALARY, GENDER, REG_DATE, JOB_ID, DEPT_ID) 
VALUES('200', 100, 'M', NULL, 'J1', '10') ;

INSERT INTO EMP_TBL(EMP_ID, SALARY, GENDER, REG_DATE, JOB_ID, DEPT_ID) 
VALUES('300', 100, 'M', DEFAULT , 'J1', '10') ;



-- 테이블 생성 후 스키마 변경 또는 제약조건에 대한 (수정, 추가) ???? 
-- ALTER (제약조건, 컬럼)
DROP TABLE IF EXISTS EMP_TBL ; 
CREATE TABLE EMP_TBL(
	EMP_ID		VARCHAR(10),
	EMP_NAME		VARCHAR(50),
	SALARY		INT				CHECK( SALARY > 0 ),
	GENDER		CHAR(1)			CHECK( GENDER IN('M', 'F')),
	REG_DATE		DATE				DEFAULT SYSDATE(),
	JOB_ID		VARCHAR(10) 	NOT NULL , 
	DEPT_ID		VARCHAR(10) 	NOT NULL 
);

SELECT	*
FROM	 	EMP_TBL ;

ALTER TABLE 	EMP_TBL
-- ADD, DROP CONSTRIANT

-- ADD COLUMN 
-- MODIFY COLUMN	COLUMN_NAME TYPE -- 타입변경시(데이터 유무 판단)
-- CHANGE COLUMN OLD NEW INT
-- DROP COLUMN EMP_ID

-- RENAME NEW_TABLE_NAME -- 테이블 이름 변경
ALTER TABLE 	EMP_TBL
ADD CONSTRAINT  PRIMARY KEY(EMP_ID) ;

ALTER TABLE 	EMP_TBL
ADD CONSTRAINT FOREIGN KEY(DEPT_ID) REFERENCES DEPT_TBL(DEPT_ID) ;

ALTER TABLE 	EMP_TBL
ADD CONSTRAINT FOREIGN KEY(JOB_ID)  REFERENCES JOB_TBL(JOB_ID) ; 


ALTER TABLE 	EMP_TBL
ADD COLUMN MARRIAGE CHAR(1) DEFAULT 'M' CHECK( MARRIAGE IN ('M', 'F')) ; 

SELECT	*
FROM	 	EMP_TBL ;


ALTER TABLE COMPOSIT_CHILD_TBL DROP CONSTRAINT FK_CHILD_TO_PARENT;
DROP TABLE COMPOSIT_TBL;

CREATE TABLE COMPOSIT_TBL(
	COPY_ID		VARCHAR(10),
	TITLE_ID		VARCHAR(10),
	STATUS 		VARCHAR(10), 
	CONSTRAINT PRIMARY KEY(COPY_ID, TITLE_ID)	
) ;
 
SELECT	*
FROM		COMPOSIT_TBL ; 

-- Q) COMPOSIT_TBL로부터 기본키를 전이받는 COMPOSIT_CHILD_TBL 생성
-- 전이받은 외래키와 CHILD_ID 컬럼을 조합해서 기본키를 생성
-- 일반컬럼으로는 REG_DATE
-- 테이블 생성 후 부모, 자식에 더미 데이터 입력해서 확인 

DROP TABLE IF EXISTS COMPOSIT_CHILD_TBL;
CREATE TABLE COMPOSIT_CHILD_TBL(
	CHILD_ID VARCHAR(10),
	COPY_ID VARCHAR(10),
	TITLE_ID VARCHAR(10),
	REG_DATE DATE			DEFAULT SYSDATE(),
	
	CONSTRAINT FK_CHILD_TO_PARENT FOREIGN KEY (COPY_ID, TITLE_ID) REFERENCES COMPOSIT_TBL(COPY_ID, TITLE_ID) ,
	CONSTRAINT PK_COMPOSIT_CHILD PRIMARY KEY(CHILD_ID,COPY_ID,TITLE_ID)
);
SELECT	*
FROM		COMPOSIT_CHILD_TBL ; 

/*
-- VIEW : 가상의 논리적 테이블(읽기전용)
-- 목적 : 보안 및 질의어의 단순화

CREATE OR REPLACE VIEW VIEW_NAME(alias)
AS SUBQUERY;
*/
CREATE OR REPLACE VIEW EMP_VIEW(NAME, DEPT)
AS
SELECT	E.EMP_NAME,
			D.DEPT_NAME	
FROM		employee		E
JOIN		department	D ON(E.DEPT_ID = D.DEPT_ID)
WHERE		E.DEPT_ID = '90' ;

SELECT	*
FROM		EMP_VIEW

/*

AUDTO_INCREMENT

SEQUENCE : 중복되지않는 값을 채번
-- 기본키의 값으

CREATE SEQUENCE SEQUENCE_NAME
START WITH 1
INCREMENT BY 1;

NEXTVAL() : 새로운값을 생성
LASTVAL() : 현재값을 반환

*/

CREATE SEQUENCE TEST_SEQ;

SELECT	NEXTVAL(TEST_SEQ);
SELECT	LASTVAL(TEST_SEQ);

-- 인라인 뷰를 활용한 TOP - N 분석

-- Q) 부서별 평균 급여 VIEW 작성
-- 평균 급여 계산의 편의를 위해서 정수자리 세자리에서 반올림

-- DROP VIEW VIEW_NAME
CREATE OR REPLACE VIEW DEPT_AVG_VIEW(DEPT_ID, DEPT_AVG)
AS
SELECT	DEPT_ID,
			ROUND(AVG(SALARY),-3)
FROM		employee
GROUP BY DEPT_ID;

SELECT *
FROM DEPT_AVG_VIEW;

SELECT	EMP_NAME,
			SALARY
FROM		(	SELECT	DEPT_ID,
							ROUND(AVG(SALARY), -3) AS DEPT_AVG
				FROM		employee
				GROUP BY	DEPT_ID	) INLV
JOIN		employee E ON (E.DEPT_ID = INLV.DEPT_ID)
WHERE		SALARY > INLV.DEPT_AVG;

SELECT	RNUM,
			EMP_NAME,
			SALARY
FROM		(SELECT	ROW_NUMBER() OVER(ORDER BY SALARY DESC) RNUM ,
						EMP_NAME, 
						SALARY
			FROM		(	SELECT	DEPT_ID,
										ROUND(AVG(SALARY), -3) AS DEPT_AVG
							FROM		employee
							GROUP BY DEPT_ID ) AS INLV
			JOIN		employee E ON (E.DEPT_ID = INLV.DEPT_ID) 
			WHERE		SALARY > INLV.DEPT_AVG) AS TOP
WHERE		RNUM <= 3 ;

-- DML(Data Manipulation Language)
-- update, insert, delete, transaction(commit, rollback), lock

/*
UPDATE 구문

UPDATE 	TABLE_NAME
SET 		COLUMN_NAME = VALUE | SUBQUERY | DEFAULT ,[COLUMN_NAME = VALUE]
*/

SELECT	*
FROM		department;

UPDATE	department
SET		DEPT_NAME = '해외영업3팀'
WHERE		DEPT_ID = 90;

ROLLBACK;

COMMIT;

SELECT *
FROM employee;

-- Q)심하균의 직급과 부서를 성해교 사원과 같은 직급과 부서로 수정한다면?
UPDATE    employee
SET        JOB_ID = (SELECT JOB_ID FROM EMPLOYEE WHERE EMP_NAME = '성해교'),
           DEPT_ID = (SELECT DEPT_ID FROM EMPLOYEE WHERE EMP_NAME = '성해교')
WHERE        EMP_NAME = '심하균';

-- Q)한선기 기혼자를 돌싱으로 수정한다면?
UPDATE 	employee
SET		MARRIAGE = DEFAULT
WHERE		EMP_ID = '100';

-- 데이터의 무결성 고민이 필요함
-- ERROR
UPDATE 	employee
SET		DEPT_ID = '65'
WHERE		EMP_ID = '100'

-- INSERT : 행 추가
/*
INSERT INTO TABLE_NAME(COLUMN ....)
VALUES (VALUE1, VALUE2, ....)
*/

INSERT INTO employee()
VALUES('900', '임정섭', 'XXXXXX-XXXXXXX', 'JSLIM@VCC.COM', '010XXXXXXXX', SYSDATE(), NULL, 1000000, NULL, 'Y', '100', NULL);

CREATE TEMPORARY TABLE IF NOT EXISTS TEMP_TBL(
	EMP_ID		CHAR(3),
	EMP_NAME		VARCHAR(20),
	DEPT_NAME	VARCHAR(20)
);

INSERT INTO TEMP_TBL
SELECT	EMP_ID,
			EMP_NAME,
			DEPT_NAME
FROM		employee E
JOIN		department D ON (E.DEPT_ID = D.DEPT_ID);

SELECT *
FROM TEMP_TBL;

/*
DELETE : 데이터를 행 단위로 삭제하는 것
DROP : 구조와 데이터를 모두 삭제
무결성 : 

DELETE
FROM 		TABLE_NAME
WHERE		CONDITION;
*/

DELETE
FROM		employee
WHERE		EMP_ID = '900';


CREATE TABLE user_tbl(
	EMAIL	VARCHAR(100),
	PASSWORD VARCHAR(100),
	NAME	VARCHAR(100),
	CONSTRAINT PRIMARY KEY(EMAIL)
);

SELECT *
FROM	user_tbl;

DROP TABLE IF EXISTS BLOG_TBL;
CREATE TABLE BLOG_TBL(
	ID 		INT, 
	TITLE 	VARCHAR(100),
	CONTENT	VARCHAR(500),
	EMAIL 	VARCHAR(100),
	CONSTRAINT PRIMARY KEY(ID),
	CONSTRAINT FOREIGN KEY (EMAIL) REFERENCES user_tbl(EMAIL)
);

DROP SEQUENCE BLOG_SEQ;
CREATE SEQUENCE BLOG_SEQ;
INSERT INTO BLOG_TBL
VALUES(NEXTVAL(BLOG_SEQ), '육이오', '호국보훈의 달', 'sample@google.com'); 

SELECT	*
FROM		BLOG_TBL;

DROP TABLE IF EXISTS BLOG_COMMENT_TBL;
CREATE TABLE BLOG_COMMENT_TBL(
	ID 		INT,
	COMMENT 	VARCHAR(100),
	EMAIL 	VARCHAR(100),
	BLOGID	INT,
	CONSTRAINT PRIMARY KEY(ID),
	CONSTRAINT FOREIGN KEY (BLOGID) REFERENCES BLOG_TBL(ID)
);

SELECT	*
FROM 		BLOG_COMMENT_TBL;

DROP SEQUENCE IF EXISTS COMMENT_SEQ;
CREATE SEQUENCE COMMENT_SEQ;

INSERT INTO BLOG_COMMENT_TBL
VALUES
(NEXTVAL(COMMENT_SEQ), '댓글', 'jslim9413@naver.com', 1),
(NEXTVAL(COMMENT_SEQ), '2등', 'lgcns@naver.com', 1);

INSERT INTO BLOG_COMMENT_TBL
VALUES(NEXTVAL(COMMENT_SEQ), '휴 성공했습니다', 'sample@google.com', 1);