

-- 1)
DROP TABLE IF EXISTS TB_CATEGORY
CREATE TABLE TB_CATEGORY(
	NAME VARCHAR(10),
	USE_YN CHAR(1) DEFAULT 'Y'
);
SELECT *
FROM TB_CATEGORY;

-- 2)
DROP TABLE IF EXISTS TB_CLASS_TYPE
CREATE TABLE TB_CLASS_TYPE(
	NO VARCHAR(5),
	NAME VARCHAR(10),
	CONSTRAINT  PRIMARY KEY(NO)
);
SELECT *
FROM TB_CLASS_TYPE;

-- 3)
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT  PRIMARY KEY(NAME) ;

-- 4)
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME	VARCHAR(5) NOT NULL;

-- 5)
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR(10),
MODIFY NAME VARCHAR(20);

-- 6)
ALTER TABLE TB_CATEGORY 
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE 
RENAME COLUMN NO TO CLASS_TYPE_NO,
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

-- 7)
ALTER TABLE TB_CATEGORY
RENAME COLUMN NO 

ALTER TABLE TB_CLASS_TYPE 
