

-- 1)
DROP TABLE IF EXISTS TB_CATEGORY
CREATE TABLE TB_CATEGORY(
	NAME VARCHAR(10),
	USE_YN CHAR(1) DEFAULT 'Y'
);
SELECT *
FROM TB_CATEGORY;

-- 2)
DROP TABLE IF EXISTS TB_CLASS_TYPE
CREATE TABLE TB_CLASS_TYPE(
	NO VARCHAR(5),
	NAME VARCHAR(10),
	CONSTRAINT  PRIMARY KEY(NO)
);
SELECT *
FROM TB_CLASS_TYPE;

-- 3)
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT  PRIMARY KEY(NAME) ;

-- 4)
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME	VARCHAR(5) NOT NULL;

-- 5)
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR(10),
MODIFY NAME VARCHAR(20);

-- 6)
ALTER TABLE TB_CATEGORY 
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE 
RENAME COLUMN NO TO CLASS_TYPE_NO,
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

-- 7)
ALTER TABLE TB_CATEGORY
DROP CONSTRAINT PRIMARY KEY,
ADD CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY (CATEGORY_NAME);
ALTER TABLE tb_class_type
DROP CONSTRAINT PRIMARY KEY,
ADD CONSTRAINT PK_CLASS_TYPE_NO PRIMARY KEY (CLASS_TYPE_NO);

-- 8)
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9)
SELECT *
FROM tb_department;

ALTER TABLE tb_department
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY)  REFERENCES TB_CATEGORY(CATEGORY_NAME);


-- 15)
SELECT
   C.CLASS_NO AS `과목번호`
,  C.CLASS_NAME AS `과목이름`
,  COUNT(C.CLASS_NO) AS `누적수강생수(명)`
FROM 
   TB_GRADE G
JOIN 
   tb_class C ON G.CLASS_NO = C.CLASS_NO
WHERE 
   CAST(LEFT(G.TERM_NO, 4) AS UNSIGNED) BETWEEN
   (
      SELECT 
			MAX(CAST(LEFT(TERM_NO, 4) AS UNSIGNED)) - 2
      FROM 
			TB_GRADE
   ) AND (
      SELECT 
			MAX(CAST(LEFT(TERM_NO, 4) AS UNSIGNED))
      FROM 
			TB_GRADE
   )
GROUP BY 
   C.CLASS_NO 
,  C.CLASS_NAME
ORDER BY 
	COUNT(*) DESC
LIMIT 3;